### ISSUE TITLE
Alloy* vs Nitpick (Isabelle/HOL)

### ISSUE THREAD

**Issue by hnemati** [aleksandarmilicevic/hola#10]
How would you compare Alloy* with Nitpick in handling Higher Order formulas? Are these two tools comparable?

**Comment by aleksandarmilicevic** [comment]
Unfortunately, I am not too familiar with Nitpick (although I should have been when I was working on Alloy*).

Based on a quick reading of their [itp-2010 paper](https://link.springer.com/chapter/10.1007/978-3-642-14052-5_11), the following stood out to me:

> <img width="608" alt="Screen Shot 2019-06-17 at 1 18 38 PM" src="https://user-images.githubusercontent.com/3605293/59634286-47615000-9103-11e9-904f-2de713c6c804.png">

Based on this, it seems that the Nitpick translation only targets the First-Order Relational Logic (FORL) segment supported by Kodkod.  To handle HOL formulas, Nitpick has to play various tricks in order to avoid generating higher-order Kodkod formulas (e.g., generate, what they call, "unwieldy n-tuple representation of functions").  

In contrast, the Alloy* work extends Kodkod to admit higher-order formulas.  In other words, the preferred translation (mentioned in the quoted paragraph above) is now readily solvable by the Alloy* version of Kodkod, so none of the listed workarounds are necessary.  It would be very interesting to compare the two approaches and see which one works better for Nitpick: (1) the existing workaround vs. (2) translating directly to higher-order Kodkod formulas.

**Comment by hnemati** [comment]
Thanks for the prompt reply and clarification! Do you think if Alloy* can handle security properties like [Non-interference](https://en.wikipedia.org/wiki/Non-interference_(security))?

**Comment by aleksandarmilicevic** [comment]
It should be possible to conceptually model this property in Alloy* and check that for all possible sequences of low inputs no matter what the values of high inputs are the result stays the same.

**Comment by hnemati** [comment]
Thanks Aleksandar!
